/*============================================================================*/
#ifndef SHISHGL_COLOR_COLLECTION_HPP
#define SHISHGL_COLOR_COLLECTION_HPP
/*============================================================================*/
#include "Color.hpp"
/*============================================================================*/
namespace ShishGL::COLOR {

    /* generated by scripts/prettify_colors.py */
    /*----------------------------------------------------------*/
    constexpr Color NONE                     {0,     0,   0,   0};
    constexpr Color INDIAN_RED               {205,  92,  92, 255};
    constexpr Color LIGHT_CORAL              {240, 128, 128, 255};
    constexpr Color SALMON                   {250, 128, 114, 255};
    constexpr Color DARK_SALMON              {233, 150, 122, 255};
    constexpr Color LIGHT_SALMON             {255, 160, 122, 255};
    constexpr Color CRIMSON                  {220,  20,  60, 255};
    constexpr Color RED                      {255,   0,   0, 255};
    constexpr Color FIRE_BRICK               {178,  34,  34, 255};
    constexpr Color DARK_RED                 {139,   0,   0, 255};
    constexpr Color PINK                     {255, 192, 203, 255};
    constexpr Color LIGHT_PINK               {255, 182, 193, 255};
    constexpr Color HOT_PINK                 {255, 105, 180, 255};
    constexpr Color DEEP_PINK                {255,  20, 147, 255};
    constexpr Color MEDIUM_VIOLET_RED        {199,  21, 133, 255};
    constexpr Color PALE_VIOLET_RED          {219, 112, 147, 255};
    constexpr Color CORAL                    {255, 127,  80, 255};
    constexpr Color TOMATO                   {255,  99,  71, 255};
    constexpr Color ORANGE_RED               {255,  69,   0, 255};
    constexpr Color DARK_ORANGE              {255, 140,   0, 255};
    constexpr Color ORANGE                   {255, 165,   0, 255};
    constexpr Color GOLD                     {255, 215,   0, 255};
    constexpr Color YELLOW                   {255, 255,   0, 255};
    constexpr Color LIGHT_YELLOW             {255, 255, 224, 255};
    constexpr Color LEMON_CHIFFON            {255, 250, 205, 255};
    constexpr Color LIGHT_GOLDENROD_YELLOW   {250, 250, 210, 255};
    constexpr Color PAPAYA_WHIP              {255, 239, 213, 255};
    constexpr Color MOCCASIN                 {255, 228, 181, 255};
    constexpr Color PEACH_PUFF               {255, 218, 185, 255};
    constexpr Color PALE_GOLDENROD           {238, 232, 170, 255};
    constexpr Color KHAKI                    {240, 230, 140, 255};
    constexpr Color DARK_KHAKI               {189, 183, 107, 255};
    constexpr Color LAVENDER                 {230, 230, 250, 255};
    constexpr Color THISTLE                  {216, 191, 216, 255};
    constexpr Color PLUM                     {221, 160, 221, 255};
    constexpr Color VIOLET                   {238, 130, 238, 255};
    constexpr Color ORCHID                   {218, 112, 214, 255};
    constexpr Color FUCHSIA                  {255,   0, 255, 255};
    constexpr Color MAGENTA                  {255,   0, 255, 255};
    constexpr Color MEDIUM_ORCHID            {186,  85, 211, 255};
    constexpr Color MEDIUM_PURPLE            {147, 112, 219, 255};
    constexpr Color BLUE_VIOLET              {138,  43, 226, 255};
    constexpr Color DARK_VIOLET              {148,   0, 211, 255};
    constexpr Color DARK_ORCHID              {153,  50, 204, 255};
    constexpr Color DARK_MAGENTA             {139,   0, 139, 255};
    constexpr Color PURPLE                   {128,   0, 128, 255};
    constexpr Color INDIGO                   { 75,   0, 130, 255};
    constexpr Color SLATE_BLUE               {106,  90, 205, 255};
    constexpr Color DARK_SLATE_BLUE          { 72,  61, 139, 255};
    constexpr Color CORNSILK                 {255, 248, 220, 255};
    constexpr Color BLANCHED_ALMOND          {255, 235, 205, 255};
    constexpr Color BISQUE                   {255, 228, 196, 255};
    constexpr Color NAVAJO_WHITE             {255, 222, 173, 255};
    constexpr Color WHEAT                    {245, 222, 179, 255};
    constexpr Color BURLY_WOOD               {222, 184, 135, 255};
    constexpr Color TAN                      {210, 180, 140, 255};
    constexpr Color ROSY_BROWN               {188, 143, 143, 255};
    constexpr Color SANDY_BROWN              {244, 164,  96, 255};
    constexpr Color GOLDENROD                {218, 165,  32, 255};
    constexpr Color DARK_GOLDEN_ROD          {184, 134,  11, 255};
    constexpr Color PERU                     {205, 133,  63, 255};
    constexpr Color CHOCOLATE                {210, 105,  30, 255};
    constexpr Color SADDLE_BROWN             {139,  69,  19, 255};
    constexpr Color SIENNA                   {160,  82,  45, 255};
    constexpr Color BROWN                    {165,  42,  42, 255};
    constexpr Color MAROON                   {128,   0,   0, 255};
    constexpr Color BLACK                    {  0,   0,   0, 255};
    constexpr Color GRAY                     {128, 128, 128, 255};
    constexpr Color SILVER                   {192, 192, 192, 255};
    constexpr Color WHITE                    {255, 255, 255, 255};
    constexpr Color OLIVE                    {128, 128,   0, 255};
    constexpr Color LIME                     {  0, 255,   0, 255};
    constexpr Color GREEN                    {  0, 128,   0, 255};
    constexpr Color AQUA                     {  0, 255, 255, 255};
    constexpr Color TEAL                     {  0, 128, 128, 255};
    constexpr Color BLUE                     {  0,   0, 255, 255};
    constexpr Color NAVY                     {  0,   0, 128, 255};
    constexpr Color GREEN_YELLOW             {173, 255,  47, 255};
    constexpr Color CHARTREUSE               {127, 255,   0, 255};
    constexpr Color LAWN_GREEN               {124, 252,   0, 255};
    constexpr Color LIME_GREEN               { 50, 205,  50, 255};
    constexpr Color PALE_GREEN               {152, 251, 152, 255};
    constexpr Color LIGHT_GREEN              {144, 238, 144, 255};
    constexpr Color MEDIUM_SPRING_GREEN      {  0, 250, 154, 255};
    constexpr Color SPRING_GREEN             {  0, 255, 127, 255};
    constexpr Color MEDIUM_SEA_GREEN         { 60, 179, 113, 255};
    constexpr Color SEA_GREEN                { 46, 139,  87, 255};
    constexpr Color FOREST_GREEN             { 34, 139,  34, 255};
    constexpr Color DARK_GREEN               {  0, 100,   0, 255};
    constexpr Color YELLOW_GREEN             {154, 205,  50, 255};
    constexpr Color OLIVE_DRAB               {107, 142,  35, 255};
    constexpr Color DARK_OLIVE_GREEN         { 85, 107,  47, 255};
    constexpr Color MEDIUM_AQUAMARINE        {102, 205, 170, 255};
    constexpr Color DARK_SEA_GREEN           {143, 188, 143, 255};
    constexpr Color LIGHT_SEA_GREEN          { 32, 178, 170, 255};
    constexpr Color DARK_CYAN                {  0, 139, 139, 255};
    constexpr Color CYAN                     {  0, 255, 255, 255};
    constexpr Color LIGHT_CYAN               {224, 255, 255, 255};
    constexpr Color PALE_TURQUOISE           {175, 238, 238, 255};
    constexpr Color AQUAMARINE               {127, 255, 212, 255};
    constexpr Color TURQUOISE                { 64, 224, 208, 255};
    constexpr Color MEDIUM_TURQUOISE         { 72, 209, 204, 255};
    constexpr Color DARK_TURQUOISE           {  0, 206, 209, 255};
    constexpr Color CADET_BLUE               { 95, 158, 160, 255};
    constexpr Color STEEL_BLUE               { 70, 130, 180, 255};
    constexpr Color LIGHT_STEEL_BLUE         {176, 196, 222, 255};
    constexpr Color POWDER_BLUE              {176, 224, 230, 255};
    constexpr Color LIGHT_BLUE               {173, 216, 230, 255};
    constexpr Color SKY_BLUE                 {135, 206, 235, 255};
    constexpr Color LIGHT_SKY_BLUE           {135, 206, 250, 255};
    constexpr Color DEEP_SKY_BLUE            {  0, 191, 255, 255};
    constexpr Color DODGER_BLUE              { 30, 144, 255, 255};
    constexpr Color CORNFLOWER_BLUE          {100, 149, 237, 255};
    constexpr Color MEDIUM_SLATE_BLUE        {123, 104, 238, 255};
    constexpr Color ROYAL_BLUE               { 65, 105, 225, 255};
    constexpr Color MEDIUM_BLUE              {  0,   0, 205, 255};
    constexpr Color DARK_BLUE                {  0,   0, 139, 255};
    constexpr Color MIDNIGHT_BLUE            { 25,  25, 112, 255};
    constexpr Color SNOW                     {255, 250, 250, 255};
    constexpr Color HONEYDEW                 {240, 255, 240, 255};
    constexpr Color MINT_CREAM               {245, 255, 250, 255};
    constexpr Color AZURE                    {240, 255, 255, 255};
    constexpr Color ALICE_BLUE               {240, 248, 255, 255};
    constexpr Color GHOST_WHITE              {248, 248, 255, 255};
    constexpr Color WHITE_SMOKE              {245, 245, 245, 255};
    constexpr Color SEASHELL                 {255, 245, 238, 255};
    constexpr Color BEIGE                    {245, 245, 220, 255};
    constexpr Color OLD_LACE                 {253, 245, 230, 255};
    constexpr Color FLORAL_WHITE             {255, 250, 240, 255};
    constexpr Color IVORY                    {255, 255, 240, 255};
    constexpr Color ANTIQUE_WHITE            {250, 235, 215, 255};
    constexpr Color LINEN                    {250, 240, 230, 255};
    constexpr Color LAVENDER_BLUSH           {255, 240, 245, 255};
    constexpr Color MISTY_ROSE               {255, 228, 225, 255};
    constexpr Color GAINSBORO                {220, 220, 220, 255};
    constexpr Color LIGHT_GREY               {211, 211, 211, 255};
    constexpr Color LIGHT_GRAY               {211, 211, 211, 255};
    constexpr Color DARK_GRAY                {169, 169, 169, 255};
    constexpr Color DARK_GREY                {169, 169, 169, 255};
    constexpr Color GREY                     {128, 128, 128, 255};
    constexpr Color DIM_GRAY                 {105, 105, 105, 255};
    constexpr Color DIM_GREY                 {105, 105, 105, 255};
    constexpr Color LIGHT_SLATE_GRAY         {119, 136, 153, 255};
    constexpr Color LIGHT_SLATE_GREY         {119, 136, 153, 255};
    constexpr Color SLATE_GRAY               {112, 128, 144, 255};
    constexpr Color SLATE_GREY               {112, 128, 144, 255};
    constexpr Color DARK_SLATE_GRAY          { 47,  79,  79, 255};
    constexpr Color DARK_SLATE_GREY          { 47,  79,  79, 255};
    /*----------------------------------------------------------*/

}
/*============================================================================*/
#endif //SHISHGL_COLOR_COLLECTION
/*============================================================================*/
